# Generated by Django 4.2.13 on 2026-02-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_materialview_materialdownload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='file_url',
        ),
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
    ]
