# Generated by Django 4.2.13 on 2026-02-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_remove_material_file_url_material_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='file',
        ),
        migrations.AddField(
            model_name='material',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
